# Generated by Django 5.0 on 2024-02-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='user_verify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.userinfo'),
        ),
    ]
