# Generated by Django 5.0 on 2024-02-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_userinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
    ]
