# Generated by Django 5.0 on 2024-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='email_token',
            field=models.IntegerField(),
        ),
    ]
