# Generated by Django 5.0 on 2024-02-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_emailverify_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='user_verify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify', to='login.userinfo'),
        ),
    ]
